version: '3'
services:
  main:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      dockerfile: Dockerfile
      context: ./main
    volumes:
      # map files from ./main to /app inside container
      # every time that something asks to a file in /app inside the container
      # it will search in ./main from current directory
      - ./main:/app
    deploy:
      resources:
        limits:
          # cpus: '0.001'
          memory: 30M
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - './files/remote1:/home/username/'
      - './files/pass:/etc/pure-ftpd/passwd'
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: username
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/username
    restart: always
 
   
   