version: '3'
services:
  main:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      dockerfile: Dockerfile
      context: ./main
    volumes:
      # map files from ./main to /app inside container
      # every time that something asks to a file in /app inside the container
      # it will search in ./main from current directory
      - ./main:/app
    deploy:
      resources:
        limits:
          # cpus: '0.001'
          memory: 30M
  remote:
    build:
      dockerfile: Dockerfile
      context: ./remote
    volumes:
      # map files from ./remote to /app inside container
      # every time that something asks to a file in /app inside the container
      # it will search in ./remote from current directory
      - ./remote:/app
    ports:
      - '5001:5001'
    deploy:
      resources:
        limits:
          # cpus: '0.001'
          memory: 20M


  # client:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./client
  #   volumes:
  #     - /app/node_modules
  #     - ./client:/app
  # worker:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./worker
  #   volumes:
  #     - /app/node_modules
  #     - ./worker:/app
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379